App\Entity\Location:
  properties:
    name:
      - NotBlank:
          groups: ['new', 'edit']
      - Regex:
          pattern: '/\d/'
          htmlPattern: false
          match: false
          message: Location name cannot contain a number
          groups: ['new', 'edit']
    longitude:
      - Regex:
          pattern: '/\d/'
          htmlPattern: false
          message: Longitude must be a number
          groups: [ 'new', 'edit' ]
      - Range:
          min: -180
          max: 180
          groups: ['new', 'edit']
    latitude:
      - Regex:
          pattern: '/\d/'
          htmlPattern: false
          message: Latitude must be a number
          groups: [ 'new', 'edit' ]
      - Range:
          min: -90
          max: 90
          groups: ['new', 'edit']

App\Entity\Measurement:
  properties:
    temperature:
      - Regex:
          pattern: '/\d/'
          htmlPattern: false
          message: Temperature must be a number
          groups: ['new', 'edit']
      - Range:
          min: -999.99
          max: 999.99
          groups: ['new', 'edit']
    wind_speed:
      - Regex:
          pattern: '/\d/'
          htmlPattern: false
          message: Wind speed must be a number
          groups: ['new', 'edit']
      - Range:
          min: -999.99
          max: 999.99
          groups: ['new', 'edit']
    humidity:
      - Regex:
          pattern: '/\d/'
          htmlPattern: false
          message: Humidity must be a number
          groups: ['new', 'edit']
      - Range:
          min: 0.0
          max: 1.0
          groups: ['new', 'edit']
